name: Dump

on:
  workflow_dispatch:
    inputs:
      enable-context:
        type: choice
        required: true
        options:
          - "true"
          - "false"

defaults:
  run:
    shell: bash

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/dump
        id: dump
        with:
          enable-context: ${{ inputs.enable-context }}

      - run: echo "${DATE}"
        env:
          DATE: ${{ steps.dump.outputs.dumped-date }}
